# Generated by Django 3.1 on 2020-08-22 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0004_userquiz_userquizanswer'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='userquiz',
            constraint=models.UniqueConstraint(condition=models.Q(completed_at__isnull=True), fields=('user',), name='unique_running_quiz_user'),
        ),
    ]
