# Generated by Django 3.1 on 2020-08-22 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0005_auto_20200822_0458'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='submitted_answers',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='question',
            name='submitted_correct_answers',
            field=models.IntegerField(default=0),
        ),
    ]
